[blame]
  coloring = highlightRecent
[color "advice"]
  hint = bold italic
[color "decorate"]
  branch = 100
[color "blame"]
  highlightRecent = 57,24.months.ago,58,6.months.ago,59,1.month.ago,60,5.days.ago,61
  repeatedLines = 96
[color "branch"]
  current = 49
  local = 50
  remote = 51
  upstream = 52
  plain = 48
[color "diff"]
  context = 101
  meta = 105
  frag = 98
  func = 7
  old = 38
  new = 36
  commit = 55
  whitespace = 97 bold
  oldMoved = 39
  newMoved = 39
  oldMovedDimmed = 39 dim
  oldMovedAlternative = 39 233
  oldMovedAlternativeDimmed = 39 dim 233
  newMovedDimmed = 39 dim
  newMovedAlternative = 39 233
  newMovedAlternativeDimmed = 39 dim 233
  contextDimmed = 101 dim
  oldDimmed = 38 dim
  newDimmed = 36 dim
  contextBold = 101 bold
  oldBold = 38 bold
  newBold = 36 bold
[color "decorate"]
  branch = 48
  remoteBranch = 51
  tag = 47
  stash = 48
  HEAD = 49
  grafted = 48
[color "grep"]
  context = 101
  filename = 105
  function = 105
  lineNumber = 96
  column = 96
  match = 102
  selected = 100
  separator = 96
[color "interactive"]
  prompt = 7
  header = 98
  help = 94 95
  error = 92 bold 93
[color "push"]
  error = 92 bold 93
[color "remote"]
  hint = bold
  warning = 94 95
  success = green bold
  error = 92 bold 93
[color "status"]
  header = 7
  added = 36
  changed = 37
  untracked = 26
  branch = 49
  nobranch = 92 bold 93
  localBranch = 50
  remoteBranch = 51
  unmerged = 42
[color "transport"]
  rejected = 92 bold 93
